# Generated by Django 3.2.13 on 2022-05-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('breed', models.CharField(max_length=100, verbose_name='Rasa')),
                ('gender', models.CharField(choices=[('0', 'Samiec'), ('0', 'Samica')], max_length=6, verbose_name='Płeć')),
                ('weight', models.PositiveIntegerField(verbose_name='Waga')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Pies',
                'verbose_name_plural': 'Psy',
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('location', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Aktualna lokalizacja')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dog', verbose_name='Pies')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Trener')),
            ],
            options={
                'verbose_name': 'Spacer',
                'verbose_name_plural': 'Spacery',
            },
        ),
    ]
