# Generated by Django 3.2.13 on 2022-05-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='dog',
        ),
        migrations.AddField(
            model_name='walk',
            name='dogs',
            field=models.ManyToManyField(max_length=3, to='api.Dog', verbose_name='Pies'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], max_length=6, verbose_name='Płeć'),
        ),
    ]
