# Generated by Django 3.2.13 on 2022-05-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_is_trainer'),
        ('api', '0003_auto_20220518_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Początek')),
                ('end_time', models.TimeField(verbose_name='Koniec')),
                ('location', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Aktualna lokalizacja')),
                ('dogs', models.ManyToManyField(max_length=3, to='api.Dog', verbose_name='Psy')),
            ],
            options={
                'verbose_name': 'Spacer',
                'verbose_name_plural': 'Spacery',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.customuser')),
            ],
            options={
                'verbose_name': 'Trener',
                'verbose_name_plural': 'Trenerzy',
            },
        ),
        migrations.DeleteModel(
            name='Walk',
        ),
        migrations.AddField(
            model_name='slot',
            name='trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.trainer', verbose_name='Trener'),
        ),
    ]
