# Generated by Django 3.2.13 on 2022-05-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220523_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='dogs',
            field=models.ManyToManyField(blank=True, default=None, to='api.Dog', verbose_name='Psy'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.trainer', verbose_name='Trener'),
        ),
    ]
