# Generated by Django 3.2.13 on 2022-05-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_slot_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='dog_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Liczba zapisanych psów'),
        ),
    ]
