# Generated by Django 3.2.13 on 2022-06-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220609_1803'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='location',
        ),
        migrations.AddField(
            model_name='dog',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Usunięty'),
        ),
        migrations.AddField(
            model_name='dog',
            name='rating',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rating', verbose_name='Ocena'),
        ),
        migrations.AddField(
            model_name='slot',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Usunięty'),
        ),
        migrations.AddField(
            model_name='slot',
            name='finished',
            field=models.BooleanField(blank=True, default=False, verbose_name='Zakończony'),
        ),
        migrations.AddField(
            model_name='slot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Szerokość'),
        ),
        migrations.AddField(
            model_name='slot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Długość'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='', max_length=100, verbose_name='Rasa'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], default='', max_length=6, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Waga'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='trainer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Trener'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
