# Generated by Django 3.2.13 on 2022-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rating_evaluator'),
        ('api', '0010_auto_20220609_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='rating',
        ),
        migrations.AddField(
            model_name='dog',
            name='rating',
            field=models.ManyToManyField(default=None, null=True, to='accounts.Rating', verbose_name='Ocena'),
        ),
    ]
