# Generated by Django 3.2.13 on 2022-06-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dograting_walk'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_images', verbose_name='Zdjęcie profilowe'),
        ),
    ]
