# Generated by Django 3.2.13 on 2022-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='Trener'),
        ),
    ]
