# Generated by Django 3.2.13 on 2022-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='details',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images', verbose_name='Zdjęcie profilowe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numer telefonu'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
