# Generated by Django 3.2.13 on 2022-05-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_is_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='Trener'),
        ),
    ]
