# Generated by Django 3.2.13 on 2022-06-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220609_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oceniający'),
        ),
    ]
