# Generated by Django 3.2.13 on 2022-06-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220609_1858'),
        ('accounts', '0009_rating_evaluator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
